### ISSUE TITLE
Disabling the server build

### ISSUE THREAD

**Issue by rstoneIDBS** [egoist/vite-plugin-mix#23]
I've found this great plugin via https://dev.to/xjamundx/adding-a-rest-api-to-your-vite-server-in-5-seconds-270g

For my use case this is perfect as I only want the api to be available during development as it provides a mock version of the real apis, I don't need SSR for production and don't need the 'mixed in api' included in the build.

However I've noticed that when I run 'vite build' the 'index.html' file is missing from the 'dist' directory. I suspect this is because this plugin re-runs the build in SSR mode, the only way I've found to disable this is to set the MIX_SSR_BUILD environment variable to true before building. I tested all of the above using the default Vite React app + the config shown in the linked page above.

Is there a better way to achieve what I am doing, or does it suggest an extra config option is needed?

Thanks once again for the plugin, it provides a wealth of possibilities which I am currently investigating :)

**Comment by rstoneIDBS** [comment]
Answering my own question, I'm a newbie to Vite and have just found that it supports conditional application of plugins so the correct way to do what I was asking above is with something like:

`export default defineConfig({
  plugins: [
    react(),
    {
      ...mix({
        handler: './api.js',
      }),
      apply: 'serve'
    },
  ]
});`

in vite.config.js

**Comment by kevinmlong** [comment]
@rstoneIDBS - I'm running into a similar issue as outlined in #27. For me, I'm interested in having the Vue app be client side rendered, but want to maintain the "server side" code for some endpoints. Using the `MIX_SSR_BUILD=true` environment variable seems to disable the "server side" build entirely, but the all client side code ends up in the `dist` directory as expected. In your exploration to disable server side, did come across what I'm trying to accomplish?

**Comment by rstoneIDBS** [comment]
> @rstoneIDBS - I'm running into a similar issue as outlined in #27. For me, I'm interested in having the Vue app be client side rendered, but want to maintain the "server side" code for some endpoints. Using the `MIX_SSR_BUILD=true` environment variable seems to disable the "server side" build entirely, but the all client side code ends up in the `dist` directory as expected. In your exploration to disable server side, did come across what I'm trying to accomplish?

Sorry @kevinmlong - once I found the correct way to do what I was trying to do I didn't look into MIX_SSR_BUILD any further.
