### ISSUE TITLE
index.html missing on production build

### ISSUE THREAD

**Issue by kevinmlong** [egoist/vite-plugin-mix#27]
I'm running a vite/vue app. Under a normal build without the plugin, the `dist` directory appears to contain the correct files.
![image](https://user-images.githubusercontent.com/6371696/159103401-901b8569-e997-460b-9771-c9f2848a47c1.png)

However, after adding the plugin, running `vite build` creates the `build` directory, but the `dist` directory is missing the `index.html` file.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/6371696/159103398-4a841911-c007-4a48-ac7b-b333e01fb937.png">

**Comment by kevinmlong** [comment]
This is what the plugins part of my `vite.config.js` file looks like:

```
plugins: [vue(), svgLoader(), mix({ handler: "./src/api/index.js" })],
```

**Comment by kevinmlong** [comment]
@egoist - I should also add that if I copy the index.html file generated when the `mix()` plugin is not present, it all works as expected when running `node build/server.js`. So how do I get the index.html file to be part of the `dist` directory?

**Comment by kevinmlong** [comment]
After further review of the code, it seems the `index.html` file gets deleted [here](https://github.com/egoist/vite-plugin-mix/blob/main/src/index.ts#L80) and its contents are served up by the polka server as the default when other routes don't match. It does all seem to be working with the `node build/server.js` command. I guess there was a slight problem when I was testing earlier.

**Comment by iandoesallthethings** [comment]
Hey, I'm still having this same problem with nodeAdapter(). I'm trying to use this with sveltekit and I'm getting `Error: ENOENT: no such file or directory, open '/Users/ian/dev/sveltesockets/.svelte-kit/output/server/index.html'`

```ts
	plugins: [
		sveltekit(),
		// @ts-expect-error - vite-plugin-mix doesn't properly export its default value. See: https://github.com/egoist/vite-plugin-mix/issues/41
		mix.default({
			handler: './src/express/app.ts',
			adapter: nodeAdapter(),
		}),
		socket,
	],
```

How did you get around it?

**Comment by kujohn** [comment]
I am having this issue as well. If `mix` is removed, `index.html` shows up.
